version: '3'

services:
  django:
    build: ./GymApp
    container_name: django
    command: bash -c "python manage.py makemigrations &&
                      python manage.py showmigrations &&
                      python manage.py migrate &&
                      python manage.py runserver 0.0.0.0:3010"
    volumes:
      - .:/usr/src/app
    ports:
      - 3010:3010
    depends_on:
      - db

  db:
    restart: always
    image: postgres
    container_name: demo-postgres
    environment:
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=demo
      - POSTGRES_DB=demo
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  react:
    build: ./client
    container_name: react
    command: npm start
    ports:
      - 3000:3000
    depends_on:
      - django

volumes:
  postgres_data: